# Generated by Django 5.2.5 on 2025-08-11 23:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "code",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="assets_comp_name_65c625_idx"),
                    models.Index(fields=["code"], name="assets_comp_code_5eb148_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectors",
                        to="assets.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subsection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsections",
                        to="assets.sector",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=100, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ahu", "ahu"),
                            ("chiller", "chiller"),
                            ("split", "split"),
                            ("vrf", "vrf"),
                            ("fan_coil", "fan_coil"),
                            ("cooling_tower", "cooling_tower"),
                            ("pump", "pump"),
                            ("boiler", "boiler"),
                            ("other", "other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("in_maintenance", "in_maintenance"),
                            ("down", "down"),
                            ("decommissioned", "decommissioned"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                ("install_date", models.DateField(blank=True, null=True)),
                ("maintenance_due_at", models.DateField(blank=True, null=True)),
                (
                    "criticality",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="assets.company",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="assets.sector",
                    ),
                ),
                (
                    "subsection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="assets.subsection",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="sector",
            index=models.Index(
                fields=["company", "name"], name="assets_sect_company_ba299d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sector",
            index=models.Index(
                fields=["company", "code"], name="assets_sect_company_bee8e4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sector",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code__isnull", False)),
                fields=("company", "code"),
                name="uniq_sector_code",
            ),
        ),
        migrations.AddIndex(
            model_name="subsection",
            index=models.Index(
                fields=["sector", "name"], name="assets_subs_sector__90608f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subsection",
            index=models.Index(
                fields=["sector", "code"], name="assets_subs_sector__f91749_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="subsection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code__isnull", False)),
                fields=("sector", "code"),
                name="uniq_subsection_code",
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["status"], name="assets_asse_status_347ce9_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["type"], name="assets_asse_type_00f06e_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["brand"], name="assets_asse_brand_55f498_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["company", "sector", "subsection"],
                name="assets_asse_company_11249f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["maintenance_due_at"], name="assets_asse_mainten_8c55c6_idx"
            ),
        ),
    ]
