"""
Django settings for traknor project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

import environ  # biblioteca para leitura de variáveis de ambiente

# Caminho base do projeto
BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega variáveis de ambiente do arquivo .env, quando presente
env = environ.Env()
if (BASE_DIR / ".env").exists():
    environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# Chave secreta obtida do ambiente
SECRET_KEY = env("SECRET_KEY", default="unsafe-secret-key")

# DEBUG controlado via env
DEBUG = env.bool("DEBUG", False)

# Hosts permitidos para receber requisições
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[
    "localhost", 
    "*.localhost", 
    "acme.localhost",
    "testserver",
    "127.0.0.1"
])


# Application definition

# Apps que vivem no schema público
SHARED_APPS = (
    "tenancy",  # modelos Tenant e Domain
    "accounts",
    "django.contrib.contenttypes",
    "django.contrib.auth",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework.authtoken",
)

# Apps que existirão em cada tenant
TENANT_APPS = (
    "django.contrib.admin",
    "rest_framework",
    "core",  # API utilities e middlewares
    "sample",  # app de exemplo
    "sandbox",
)

# Ordem final das apps
INSTALLED_APPS = list(SHARED_APPS) + ["django_tenants"] + list(TENANT_APPS)

# Ativa suporte a CORS
INSTALLED_APPS += ["corsheaders"]

MIDDLEWARE = [
    "django_tenants.middleware.main.TenantMainMiddleware",  # PRIMEIRO - resolve schema antes
    "django.middleware.security.SecurityMiddleware",  # garante headers de segurança
    "corsheaders.middleware.CorsMiddleware",  # precisa vir antes de CommonMiddleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# URLs do django-tenants
PUBLIC_SCHEMA_URLCONF = "traknor.urls_public"
ROOT_URLCONF = "traknor.urls_tenant"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "traknor.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Configuração do banco usando schemas do Postgres
DATABASES = {
    "default": {
        "ENGINE": "django_tenants.postgresql_backend",
        "NAME": os.getenv("POSTGRES_DB", "traknor"),
        "USER": os.getenv("POSTGRES_USER", "postgres"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "postgres"),
        "HOST": os.getenv("POSTGRES_HOST", "db"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}

# Modelos utilizados pelo django-tenants
# Modelos utilizados pelo django-tenants
TENANT_MODEL = "tenancy.Tenant"
TENANT_DOMAIN_MODEL = "tenancy.Domain"
DOMAIN_MODEL = TENANT_DOMAIN_MODEL

# Router que garante migrações separadas por schema
DATABASE_ROUTERS = ("django_tenants.routers.TenantSyncRouter",)


# Modelo de usuário customizado
AUTH_USER_MODEL = "accounts.User"


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Configurações globais do DRF
REST_FRAMEWORK = {
    # Renderer que aplica o envelope padronizado
    "DEFAULT_RENDERER_CLASSES": ["core.api.renderers.EnvelopeJSONRenderer"],
    # Paginação com metadados e headers personalizados
    "DEFAULT_PAGINATION_CLASS": "core.api.pagination.EnvelopePageNumberPagination",
    "PAGE_SIZE": 25,
    # Handler que converte exceções em Problem Details
    "EXCEPTION_HANDLER": "core.api.exceptions.problem_exception_handler",
    # Autenticação padrão via tokens
    "DEFAULT_AUTHENTICATION_CLASSES": ["rest_framework.authentication.TokenAuthentication"],
    # Permissão padrão exige usuário autenticado
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
}

# Classes e limites de throttling globais
REST_FRAMEWORK.update(
    {
        "DEFAULT_THROTTLE_CLASSES": [
            "rest_framework.throttling.AnonRateThrottle",
            "rest_framework.throttling.UserRateThrottle",
            "rest_framework.throttling.ScopedRateThrottle",
        ],
        "DEFAULT_THROTTLE_RATES": {
            "anon": env.str("THROTTLE_ANON", "60/min"),
            "user": env.str("THROTTLE_USER", "120/min"),
            "auth_login": env.str("THROTTLE_AUTH_LOGIN", "5/min"),
        },
    }
)

# Configurações de CORS
CORS_ALLOW_CREDENTIALS = True  # necessário se houver cookies/sessão
CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS",
    default=[
        "http://localhost:5173",  # Vite
        "http://localhost:3000",  # CRA
    ],
)
CORS_EXPOSE_HEADERS = [
    "Link",
    "X-Total-Count",
    "X-Total-Pages",
    "X-Per-Page",
    "X-Current-Page",
]
CORS_PREFLIGHT_MAX_AGE = 600  # tempo de cache do preflight

# Headers e métodos adicionais permitidos
from corsheaders.defaults import default_headers  # noqa: E402

CORS_ALLOW_HEADERS = list(default_headers) + ["authorization"]
CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]

# Configurações de segurança HTTP
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SAMESITE = "Lax"

SECURE_SSL_REDIRECT = not DEBUG
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
X_FRAME_OPTIONS = "DENY"
SECURE_REFERRER_POLICY = "same-origin"
